api_key: "vrOKIvVWwrDFirTmv24t25fv2131vv"
shutdown_timeout: 120s
http_server:
  port: 2531
  cors:
    allow_origins:
logger:
  file_path: "/logs/manager/logs.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30
  max_backup: 0
  compress: false
token:
  private_key_string: "2bcb815ceffc35f2bcdc527743ba5ec1ea14774ab5e57623c9a6957d7b4153b1aa7b488970bd035e8e0c21b8a60322cf92267d010f4df751fe383b3af49e6f8b"
  public_key_string: "aa7b488970bd035e8e0c21b8a60322cf92267d010f4df751fe383b3af49e6f8b"
  access_expiry: 120s
  refresh_expiry: 168h
  issuer: quick-connect-auth-service
  access_audience: all-quick-connect-service
  refresh_audience: all-quick-connect-service
  guest_expiry: 8640h
  guest_audience: chat-service
  client_expiry: 720h
  client_audience: char-service
postgres:
  host: "localhost"
  port: 11579
  db_name: defaultdb
  password: "8SHDSgdihmMH9EQsXfRZzLHes3F3kgxa"
  username: LoPgYJqYGZ53
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 20
  conn_max_lifetime: 600
  path_of_migration: "app/managerapp/repository/migrations"
grpc_server:
  host: "localhost"
  port: 2541
user:
  user_id_cache_expiration: 86400s
  password_default_length: 25
redis:
  host: "localhost"
  port: 12434
  password: "Z9265UQfrFiCYWMMJF4uvTEmJA7rEauJ"
delivery:
  register_guest_max_hint: 10
  register_guest_duration_limit: 60s
  update_guest_max_hint: 10
  update_guest_duration_limit: 60s
internal_http_server:
  port: 2533
  cors:
    allow_origins:
grpc_server_internal:
  host: "localhost"
  port: 2542