definitions:
  cursorbased.Request:
    properties:
      cursor:
        allOf:
        - $ref: '#/definitions/types.ID'
        description: |-
          Cursor is unique identifier (ULID) of the last item from the previous page.
          If empty, it includes the first page
      limit:
        description: Limit specifies how many items to fetch.
        type: integer
    type: object
  cursorbased.Response:
    properties:
      has_more:
        description: HasMore indicates if there are mote item available to fetch.
        type: boolean
      next_cursor:
        allOf:
        - $ref: '#/definitions/types.ID'
        description: |-
          Next Counter is the ID of the last item in the current list.
          The client should user this as the `cursor` for the next request.
    type: object
  paginate.Filter:
    properties:
      operation:
        $ref: '#/definitions/paginate.FilterOperation'
      values:
        items: {}
        type: array
    type: object
  paginate.FilterOperation:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    type: integer
    x-enum-varnames:
    - FilterOperationEqual
    - FilterOperationNotEqual
    - FilterOperationGreater
    - FilterOperationGreaterEqual
    - FilterOperationLess
    - FilterOperationLessEqual
    - FilterOperationIn
    - FilterOperationNotIn
    - FilterOperationBetween
  paginate.RequestBase:
    properties:
      current_page:
        type: integer
      descending:
        type: boolean
      filters:
        additionalProperties:
          $ref: '#/definitions/paginate.Filter'
        type: object
      page_size:
        type: integer
      sort_column:
        type: string
    type: object
  paginate.ResponseBase:
    properties:
      current_page:
        type: integer
      page_size:
        type: integer
      total_numbers:
        type: integer
      total_page:
        type: integer
    type: object
  servermsg.ErrorResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  service.ChatHistoryRequest:
    properties:
      conversation_id:
        $ref: '#/definitions/types.ID'
      pagination:
        $ref: '#/definitions/cursorbased.Request'
    type: object
  service.ChatHistoryResponse:
    properties:
      paginate:
        $ref: '#/definitions/cursorbased.Response'
      results:
        items:
          $ref: '#/definitions/service.Message'
        type: array
    type: object
  service.ClientInfo:
    properties:
      avatar:
        type: string
      email:
        type: string
      fullname:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      last_online_at:
        type: string
      phone_number:
        type: string
    type: object
  service.Conversation:
    properties:
      assigned_support_id:
        $ref: '#/definitions/types.ID'
      client_user_id:
        $ref: '#/definitions/types.ID'
      closed_at:
        type: string
      created_at:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      last_message_sender_id:
        $ref: '#/definitions/types.ID'
      last_message_snippet:
        type: string
      status:
        $ref: '#/definitions/service.ConversationStatus'
      updated_at:
        type: string
    type: object
  service.ConversationDetailResponse:
    properties:
      assigned_support_id:
        $ref: '#/definitions/types.ID'
      client_info:
        $ref: '#/definitions/service.ClientInfo'
      client_user_id:
        $ref: '#/definitions/types.ID'
      closed_at:
        type: string
      created_at:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      last_message_sender_id:
        $ref: '#/definitions/types.ID'
      last_message_snippet:
        type: string
      status:
        $ref: '#/definitions/service.ConversationStatus'
      support_info:
        $ref: '#/definitions/service.SupportInfo'
      updated_at:
        type: string
    type: object
  service.ConversationStatus:
    enum:
    - new
    - open
    - closed
    - bot_handling
    type: string
    x-enum-varnames:
    - ConversationStatusNew
    - ConversationStatusOpen
    - ConversationStatusClosed
    - ConversationStatusBotHandling
  service.ListConversationsRequest:
    properties:
      paginated:
        $ref: '#/definitions/paginate.RequestBase'
      statuses:
        items:
          $ref: '#/definitions/service.ConversationStatus'
        type: array
    type: object
  service.ListConversationsResponse:
    properties:
      paginate:
        $ref: '#/definitions/paginate.ResponseBase'
      results:
        items:
          $ref: '#/definitions/service.Conversation'
        type: array
    type: object
  service.Message:
    properties:
      content:
        type: string
      conversation_id:
        $ref: '#/definitions/types.ID'
      created_at:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      message_type:
        $ref: '#/definitions/service.MessageType'
      metadata:
        additionalProperties:
          type: string
        type: object
      read_at:
        type: string
      replied_to_message_id:
        $ref: '#/definitions/types.ID'
      sender_id:
        $ref: '#/definitions/types.ID'
    type: object
  service.MessageType:
    enum:
    - text
    - media
    - system
    type: string
    x-enum-varnames:
    - MessageTypeText
    - MessageTypeMedia
    - MessageTypeSystem
  service.SupportInfo:
    properties:
      avatar:
        type: string
      fullname:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      last_online_at:
        type: string
    type: object
  types.ID:
    enum:
    - 01J00000000000000000000BOT
    type: string
    x-enum-varnames:
    - BotUserID
info:
  contact: {}
paths:
  /chats:
    post:
      consumes:
      - application/json
      description: get conversation chat history
      parameters:
      - description: get conversation chat history
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/service.ChatHistoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ChatHistoryResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: GetChatHistory
      tags:
      - Chat
  /chats/clients:
    get:
      consumes:
      - application/json
      description: client chat websocket
      produces:
      - application/json
      responses: {}
      summary: client chat websocket
      tags:
      - Websocket
  /chats/supports:
    get:
      consumes:
      - application/json
      description: client chat websocket
      produces:
      - application/json
      responses: {}
      summary: client chat websocket
      tags:
      - Websocket
  /conversations:
    post:
      consumes:
      - application/json
      description: your conversation list
      parameters:
      - description: check token validation
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/service.ListConversationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ListConversationsResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/servermsg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: OwnConversationList
      tags:
      - Chat
  /conversations/{conversationID}:
    get:
      consumes:
      - application/json
      description: close conversation for chatting
      parameters:
      - description: conversation ID
        in: path
        name: conversationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: ConversationDetail
      tags:
      - Chat
  /conversations/{conversationID}/close:
    get:
      consumes:
      - application/json
      description: close conversation for chatting
      parameters:
      - description: conversation ID
        in: path
        name: conversationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: CloseConversation
      tags:
      - Chat
  /conversations/{conversationID}/open:
    get:
      consumes:
      - application/json
      description: open conversation for chatting
      parameters:
      - description: conversation ID
        in: path
        name: conversationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: OpenConversation
      tags:
      - Chat
  /conversations/active:
    get:
      consumes:
      - application/json
      description: get user active conversation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ConversationDetailResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: GetActiveConversation
      tags:
      - Chat
  /conversations/new:
    post:
      consumes:
      - application/json
      description: new conversation list
      parameters:
      - description: check token validation
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/service.ListConversationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ListConversationsResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/servermsg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: ConversationNewList
      tags:
      - Chat
  /health-check:
    get:
      consumes:
      - application/json
      description: health check chat service
      produces:
      - application/json
      responses:
        "200":
          description: everything is good
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: health check chat service
      tags:
      - Chat
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
