definitions:
  paginate.Filter:
    properties:
      operation:
        $ref: '#/definitions/paginate.FilterOperation'
      values:
        items: {}
        type: array
    type: object
  paginate.FilterOperation:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    type: integer
    x-enum-varnames:
    - FilterOperationEqual
    - FilterOperationNotEqual
    - FilterOperationGreater
    - FilterOperationGreaterEqual
    - FilterOperationLess
    - FilterOperationLessEqual
    - FilterOperationIn
    - FilterOperationNotIn
    - FilterOperationBetween
  paginate.RequestBase:
    properties:
      current_page:
        type: integer
      descending:
        type: boolean
      filters:
        additionalProperties:
          $ref: '#/definitions/paginate.Filter'
        type: object
      page_size:
        type: integer
      sort_column:
        type: string
    type: object
  paginate.ResponseBase:
    properties:
      current_page:
        type: integer
      page_size:
        type: integer
      total_numbers:
        type: integer
      total_page:
        type: integer
    type: object
  servermsg.ErrorResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  service.Conversation:
    properties:
      assigned_support_id:
        $ref: '#/definitions/types.ID'
      client_user_id:
        $ref: '#/definitions/types.ID'
      closed_at:
        type: string
      created_at:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      last_message_sender_id:
        $ref: '#/definitions/types.ID'
      last_message_snippet:
        type: string
      status:
        $ref: '#/definitions/service.ConversationStatus'
      updated_at:
        type: string
    type: object
  service.ConversationStatus:
    enum:
    - new
    - open
    - closed
    - bot_handling
    type: string
    x-enum-varnames:
    - ConversationStatusNew
    - ConversationStatusOpen
    - ConversationStatusClosed
    - ConversationStatusBotHandling
  service.ListConversationsRequest:
    properties:
      paginated:
        $ref: '#/definitions/paginate.RequestBase'
      statuses:
        items:
          $ref: '#/definitions/service.ConversationStatus'
        type: array
    type: object
  service.ListConversationsResponse:
    properties:
      paginate:
        $ref: '#/definitions/paginate.ResponseBase'
      results:
        items:
          $ref: '#/definitions/service.Conversation'
        type: array
    type: object
  types.ID:
    enum:
    - 01J00000000000000000000BOT
    type: string
    x-enum-varnames:
    - BotUserID
info:
  contact: {}
paths:
  /chats/clients:
    get:
      consumes:
      - application/json
      description: client chat websocket
      produces:
      - application/json
      responses: {}
      summary: client chat websocket
      tags:
      - Websocket
  /chats/supports:
    get:
      consumes:
      - application/json
      description: client chat websocket
      produces:
      - application/json
      responses: {}
      summary: client chat websocket
      tags:
      - Websocket
  /conversations:
    post:
      consumes:
      - application/json
      description: your conversation list
      parameters:
      - description: check token validation
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/service.ListConversationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ListConversationsResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/servermsg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: OwnConversationList
      tags:
      - Chat
  /conversations/active:
    get:
      consumes:
      - application/json
      description: get user active conversation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Conversation'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: GetActiveConversation
      tags:
      - Chat
  /conversations/new:
    post:
      consumes:
      - application/json
      description: new conversation list
      parameters:
      - description: check token validation
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/service.ListConversationsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ListConversationsResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/servermsg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: ConversationNewList
      tags:
      - Chat
  /health-check:
    get:
      consumes:
      - application/json
      description: health check chat service
      produces:
      - application/json
      responses:
        "200":
          description: everything is good
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: health check chat service
      tags:
      - Chat
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
