definitions:
  service.Conversation:
    properties:
      assigned_support_id:
        $ref: '#/definitions/types.ID'
      client_user_id:
        $ref: '#/definitions/types.ID'
      closed_at:
        type: string
      created_at:
        type: string
      id:
        $ref: '#/definitions/types.ID'
      last_message_sender_id:
        $ref: '#/definitions/types.ID'
      last_message_snippet:
        type: string
      status:
        $ref: '#/definitions/service.ConversationStatus'
      updated_at:
        type: string
    type: object
  service.ConversationStatus:
    enum:
    - new
    - open
    - closed
    - bot_handling
    type: string
    x-enum-varnames:
    - ConversationStatusNew
    - ConversationStatusOpen
    - ConversationStatusClosed
    - ConversationStatusBotHandling
  types.ID:
    enum:
    - 01J00000000000000000000BOT
    type: string
    x-enum-varnames:
    - BotUserID
info:
  contact: {}
paths:
  /chats/clients:
    get:
      consumes:
      - application/json
      description: client chat websocket
      produces:
      - application/json
      responses: {}
      summary: client chat websocket
      tags:
      - Websocket
  /chats/supports:
    get:
      consumes:
      - application/json
      description: client chat websocket
      produces:
      - application/json
      responses: {}
      summary: client chat websocket
      tags:
      - Websocket
  /conversations/active:
    get:
      consumes:
      - application/json
      description: get user active conversation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Conversation'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - JWT: []
      summary: GetActiveConversation
      tags:
      - Chat
  /health-check:
    get:
      consumes:
      - application/json
      description: health check chat service
      produces:
      - application/json
      responses:
        "200":
          description: everything is good
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: health check chat service
      tags:
      - Chat
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
