---
shutdown_timeout: 120s
http_server:
  port: 2560
  cors:
    allow_origins:
logger:
  file_path: "/logs/storage/logs.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30
  max_backup: 0
  compress: false
  write_in_console: true
storage:
  local:
    root_path: "./uploads"
    base_url: "http://localhost:2560"
