---
shutdown_timeout: 120s
http_server:
  port: 2560
  cors:
    allow_origins:
logger:
  file_path: "/logs/storage/logs.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30
  max_backup: 0
  compress: false
  write_in_console: true
storage:
  driver: "local"
  local:
    root_path: "./uploads"
    base_url: "http://localhost:2560/downloads"
postgres:
  host: "localhost"
  port: 11579
  db_name: storage_db
  password: "8SHDSgdihmMH9EQsXfRZzLHes3F3kgxa"
  username: LoPgYJqYGZ53
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 20
  conn_max_lifetime: 600
  path_of_migration: "app/storageapp/repository/migrations"
service:
  max_file_size: 26214400 # 25M 25×1024×1024
manager_app_grpc:
  host: "localhost"
  port: 2541
  ssl_mode: false
  use_otel: false
