---
http_server:
  port: 12303
shutdown_timeout: 120s
grpc_server:
  port: 12301
  host: localhost
logger:
  file_path: "/logs/example/microservice2/logs.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30
  max_backup: 0
  compress: false
observability:
  core:
    service_name: micro2
  trace:
    mode: remote
    http_collection_endpoint: localhost:4318
    grpc_collection_endpoint: localhost:4317
    batch_timeout: 5s  # for test default its can 5 minutes!
    batch_size: 1024
    ssl_mode: false
    sampling_ratio: 1
  metric:
    mode: pull
    pull_config:
      port: 12304
postgres:
  host: "localhost"
  port: 11579
  db_name: defaultdb
  password: "8SHDSgdihmMH9EQsXfRZzLHes3F3kgxa"
  username: LoPgYJqYGZ53
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 20
  conn_max_lifetime: 600
  path_of_migration: "app/managerapp/repository/migrations"
