shutdown_timeout: 120s
http_server:
  port: 2530
  cors:
    allow_origins:
logger:
  file_path: "/logs/chat/logs.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30
  max_backup: 0
  compress: false
websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
chat:
  write_wait: 10s
  pong_wait: 60s
  max_message_size: 512
postgres:
  host: "localhost"
  port: 11579
  db_name: chat_db
  password: "8SHDSgdihmMH9EQsXfRZzLHes3F3kgxa"
  username: LoPgYJqYGZ53
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 20
  conn_max_lifetime: 600
  path_of_migration: "app/chatapp/repository/migrations"