definitions:
  servermsg.ErrorResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  service.Driver:
    enum:
    - s3
    - local
    type: string
    x-enum-varnames:
    - DriverS3
    - DriverLocal
  service.File:
    properties:
      bucket:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      driver:
        $ref: '#/definitions/service.Driver'
      id:
        $ref: '#/definitions/types.ID'
      is_confirmed:
        type: boolean
      is_public:
        type: boolean
      key:
        type: string
      mim_type:
        type: string
      name:
        type: string
      size:
        type: integer
      updated_at:
        type: string
      uploader_id:
        $ref: '#/definitions/types.ID'
    type: object
  types.ID:
    enum:
    - 01J00000000000000000000BOT
    type: string
    x-enum-varnames:
    - BotUserID
info:
  contact: {}
paths:
  /files:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file to storage (S3 or Local)
      parameters:
      - description: The file to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Is the file public?
        in: formData
        name: is_public
        type: boolean
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/service.File'
        "400":
          description: File is required
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "413":
          description: File size limit exceeded
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/servermsg.ErrorResponse'
      security:
      - JWT: []
      summary: Upload a file
      tags:
      - Storage
  /health-check:
    get:
      consumes:
      - application/json
      description: health check manager service
      produces:
      - application/json
      responses:
        "200":
          description: everything is good
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: health check
      tags:
      - Storage
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
