---
name: Admin Build And Deploy On Docker

on:
  push:
    tags:
      - 'admin/v*'

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: quick_connect
    steps:
      - name: Check Triggering Tag
        if: startsWith(github.ref, 'refs/tags/admin/v')
        run: echo "Tag ${GITHUB_REF#refs/tags/}"

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - name: Run general test
        run: make test-general

      - name: Run Admin Test
        run: make admin-test

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build
        run: make admin-build IMAGE_NAME=syntaxfa/quickconnect-admin:${GITHUB_REF#refs/tags/admin/v}

      - name: push image to docker hub
        run: docker push syntaxfa/quickconnect-admin:${GITHUB_REF#refs/tags/admin/v}
