name: PR Commit Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]

permissions: write-all

jobs:
  pr-lint:
    name: Validate PR commit title meets commit convention
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: true
