---
name: Test General Go

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
    paths:
      - 'pkg/**'
      - 'adapter/**'
      - 'outbox/**'
      - 'config/**'
      - 'cli/**'
      - 'adapter/**'

jobs:
  test_general_codes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - name: lint
        run: make test-general
